---
- name: install Apache webserver
  hosts: teste

  tasks:
       - name: install Apache webserver
         apt: name=apache2 state=latest

       - name: start apache if not started
         service:
             name: apache2
             state: started


       - name: Create directory
         file:
           path: /var/www/html/teste
           state: directory
           mode: '0755'

       - name: Create directory 2
         file:
           path: /var/www/html/teste2
           state: directory
           mode: '0755'



###teste 1
       - name: copy file teste with owner and permissions
         copy:
             src: /home/vagrant/apache/teste/index.html
             dest: /var/www/html/teste/index.html
             owner: vagrant
             group: sudo
             mode: '0644'
         notify:
         - restart apache

       - name: copy virtualhost
         copy:
             src: /home/vagrant/apache/teste/teste.com.conf
             dest: /etc/apache2/sites-available/teste.com.conf
             owner: vagrant
             group: sudo
             mode: '0644'
         notify:
         - restart apache


###teste 2
       - name: copy file teste2 with owner and permissions
         copy:
             src: /home/vagrant/apache/teste2/index.html
             dest: /var/www/html/teste2/index.html
             owner: vagrant
             group: sudo
             mode: '0644'
         notify:
         - restart apache

       - name: copy virtualhost
         copy:
             src: /home/vagrant/apache/teste2/teste2.com.conf
             dest: /etc/apache2/sites-available/teste2.com.conf
             owner: vagrant
             group: sudo
             mode: '0644'
         notify:
         - restart apache
         
         
       - name: enable site
         command: a2ensite teste.com
         notify:
         - restart apache

       - name: enable site 2
         command: a2ensite teste2.com
         notify:
         - restart apache


  handlers:
       - name: restart apache
         service:
            name: apache2
            state: reloaded
